# Generated by Django 2.1.3 on 2018-11-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_text_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option1', models.TextField()),
                ('option1_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option2', models.TextField()),
                ('option2_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option3', models.TextField()),
                ('option3_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option4', models.TextField()),
                ('option4_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('answer', models.CharField(default='', max_length=90)),
                ('subject', models.CharField(default='', max_length=90)),
                ('chapter', models.CharField(default='', max_length=90)),
                ('subtopic', models.CharField(default='', max_length=90)),
                ('difficulty', models.CharField(default='medium', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Test'),
        ),
    ]
