# Generated by Django 2.1.3 on 2018-11-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20181112_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
    ]
