# Generated by Django 2.1.3 on 2018-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20181112_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
    ]
