# Generated by Django 2.1.3 on 2018-11-22 13:59

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text_image',
            field=models.ImageField(blank=True, height_field='10px', null=True, upload_to=quiz.models.upload_location, width_field='10px'),
        ),
    ]
