# Generated by Django 2.1.3 on 2018-11-22 14:01

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20181122_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.AddField(
            model_name='question',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=quiz.models.upload_location, width_field='width_field'),
        ),
    ]
