# Generated by Django 2.1.3 on 2018-11-22 14:02

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181122_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='question',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_location),
        ),
    ]
