# Generated by Django 2.1.3 on 2018-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20181122_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
