# Generated by Django 2.1.3 on 2018-12-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20181217_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
