# Generated by Django 2.1.3 on 2018-12-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_question_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='not attempted', max_length=100),
        ),
    ]
