# Generated by Django 2.1.3 on 2018-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
