# Generated by Django 2.1.3 on 2018-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20181218_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.CharField(blank=True, default='Integrals', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics')], default='physics', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.CharField(blank=True, default='integration by substitution', max_length=90, null=True),
        ),
    ]
