# Generated by Django 2.1.3 on 2018-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20181218_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.CharField(default='Integrals', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics')], default='physics', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.CharField(default='integration by substitution', max_length=90, null=True),
        ),
    ]
