# Generated by Django 2.1.3 on 2018-11-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20181111_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_no',
        ),
    ]
