# Generated by Django 2.1.3 on 2018-11-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20181112_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option4_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
